updated gitub-action-workflow

diff --git a/.github/workflows/terraform-plan.yml b/.github/workflows/terraform-plan.yml
--- a/.github/workflows/terraform-plan.yml
+++ b/.github/workflows/terraform-plan.yml
@@ -45,7 +45,7 @@ jobs:
       - name: Terraform Plan
         id: plan
         run: |
-          terraform plan -input=false -no-color > plan.txt
+          terraform plan -input=false -no-color | tee plan.txt || echo "PLAN_FAILED=true" >> $GITHUB_ENV
           echo "plan_result=changes" >> $GITHUB_OUTPUT
 
       - name: Comment Terraform Plan on PR
